version: "3.8"
services:
    postgres:
        image: "postgres"
        ports: 
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=${POSTGRESS_PASSWORD}
            - POSTGRES_DB=sonarqube
    sonarqube:
        image: "sonarqube"
        ports:
            - "9000:9000"
        environment:
            - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
            - SONAR_JDBC_USERNAME=postgres
            - SONAR_JDBC_PASSWORD=${POSTGRESS_PASSWORD}
        volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_logs:/opt/sonarqube/logs
volumes:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs: